name: CI/CD

on: push

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Forceer Docker PATH voor de runner
        run: |
          echo "/usr/bin" >> $GITHUB_PATH
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Login to Local Harbor
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."192.168.40.135"]
              http = true
              insecure = true
          
      - name: Build and push the Docker image to Local Harbor
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/devsecops/student-app:latest

  scan:
    name: Scan
    needs: [ build ]
    runs-on: self-hosted
    steps:
      - name: Forceer Docker PATH voor de runner
        run: |
          echo "/usr/bin" >> $GITHUB_PATH
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Login to Local Harbor
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Pull image locally voor Scout
        run: docker pull ${{ secrets.REGISTRY_URL }}/devsecops/student-app:latest
          
      - name: Docker Scout CVEs
        uses: docker/scout-action@v1
        with:
          command: cves
          # local:// forceert Scout om de zojuist gepullde lokale image te gebruiken
          image: local://${{ secrets.REGISTRY_URL }}/devsecops/student-app:latest
          only-severities: critical,high
          exit-code: false
          exit-on: vulnerability
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    needs: [ scan ]
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Forceer Docker PATH voor de runner
        run: |
          echo "/usr/bin" >> $GITHUB_PATH
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Login to Local Harbor
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Start container locally for testing
        run: |
          # We geven de container nu de naam 'test-app'
          docker run -d --name test-app -p 8080:5000 ${{ secrets.REGISTRY_URL }}/devsecops/student-app:latest
          sleep 10s

      - name: Install Postman CLI
        run: |
          mkdir -p $HOME/.local/bin
          mkdir -p temp_postman
          
          # Download de Postman CLI
          curl -L -o postman-cli.tar.gz "https://dl-cli.pstmn.io/download/latest/linux64"
          
          # Pak alles uit in de tijdelijke map
          tar -xzf postman-cli.tar.gz -C temp_postman
          
          # Zoek het uitgepakte bestand (ongeacht hoe het heet) en verplaats/hernoem het naar 'postman'
          BIN_PATH=$(find temp_postman -type f | head -n 1)
          mv "$BIN_PATH" $HOME/.local/bin/postman
          
          # Geef uitvoerrechten aan het bestand
          chmod +x $HOME/.local/bin/postman

      - name: Clean up container
        if: always()
        run: |
          # Forceer het verwijderen van alléén de test-app, laat Harbor met rust!
          docker rm -f test-app

  deploy:
    name: Deploy
    needs: [ test ]
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - run: |
          sudo kubectl delete deployment --all            
          sudo kubectl apply -f ${{ github.workspace }}/kubernetes/deployment.yaml --force
          sudo kubectl apply -f ${{ github.workspace }}/kubernetes/nginx-service.yaml --force
